'use server';

/**
 * @file submit-lead.ts
 * @description Server Action for quote / callback requests.
 *
 * ENV (see .env.example):
 * - SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS
 * - LEAD_DESTINATION_EMAIL
 *
 * Never log name/phone/email to the console.
 */

import nodemailer from 'nodemailer';
import { headers } from 'next/headers';

export interface LeadAttributionPayload {
  landingPage?: string;
  referrer?: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  utmContent?: string;
  utmTerm?: string;
  firstTouchSource?: string;
  pagePath?: string;
}

export interface LeadData {
  name: string;
  phone: string;
  propertyType: string;
  /** Internal label for form origin — not shown as a business field to the user */
  formSource?: 'bottom_form' | 'quote_modal';
  /** Honeypot — must remain empty */
  website?: string;
  attribution?: LeadAttributionPayload;
}

const RATE_WINDOW_MS = 60_000;
const recentByPhone = new Map<string, number>();

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function normalizePhone(phone: string): string {
  return phone.replace(/[\s\-+()]/g, '');
}

export async function submitLead(
  data: LeadData,
): Promise<{ success: boolean; error?: string }> {
  try {
    // Honeypot: bots that fill hidden fields are silently accepted without emailing.
    if (data.website && data.website.trim().length > 0) {
      return { success: true };
    }

    if (!data.name || data.name.trim().length < 2) {
      return { success: false, error: 'Please provide a valid name.' };
    }

    const phoneRegex = /^[\d\s+\-()]{8,15}$/;
    if (!data.phone || !phoneRegex.test(data.phone.trim())) {
      return { success: false, error: 'Please provide a valid phone number.' };
    }

    const cleanName = data.name.trim();
    const cleanPhone = data.phone.trim();
    const phoneKey = normalizePhone(cleanPhone);
    const cleanProperty = data.propertyType || 'Not specified';
    const formSource = data.formSource || 'unknown';
    const attr = data.attribution || {};

    const now = Date.now();
    const last = recentByPhone.get(phoneKey);
    if (last && now - last < RATE_WINDOW_MS) {
      return {
        success: false,
        error: 'Please wait a moment before submitting again.',
      };
    }
    recentByPhone.set(phoneKey, now);

    // Best-effort IP note for operators (not sent to analytics)
    let requestHint = '';
    try {
      const h = await headers();
      const fwd = h.get('x-forwarded-for')?.split(',')[0]?.trim();
      if (fwd) requestHint = fwd;
    } catch {
      requestHint = '';
    }

    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.warn(
        '[submitLead] SMTP not configured — lead not emailed (PII not logged).',
      );
      return {
        success: false,
        error:
          'Unable to send your request right now. Please call or WhatsApp us directly.',
      };
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: Number(process.env.SMTP_PORT) || 587,
      secure: Number(process.env.SMTP_PORT) === 465,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const rows: [string, string][] = [
      ['Name', cleanName],
      ['Phone', cleanPhone],
      ['Property / service', cleanProperty],
      ['Form source', formSource],
      ['Page path', attr.pagePath || '—'],
      ['Landing page', attr.landingPage || '—'],
      ['Referrer', attr.referrer || '—'],
      ['First-touch source', attr.firstTouchSource || '—'],
      ['UTM source', attr.utmSource || '—'],
      ['UTM medium', attr.utmMedium || '—'],
      ['UTM campaign', attr.utmCampaign || '—'],
      ['UTM content', attr.utmContent || '—'],
      ['UTM term', attr.utmTerm || '—'],
    ];
    if (requestHint) rows.push(['Request IP (proxy)', requestHint]);

    const htmlBody = `
      <h2>New Website Lead</h2>
      <table style="text-align: left; border-collapse: collapse; width: 100%; max-width: 560px;">
        ${rows
          .map(
            ([k, v]) =>
              `<tr><th style="padding: 8px; border: 1px solid #ddd;">${escapeHtml(k)}</th><td style="padding: 8px; border: 1px solid #ddd;">${
                k === 'Phone'
                  ? `<a href="tel:${escapeHtml(v)}">${escapeHtml(v)}</a>`
                  : escapeHtml(v)
              }</td></tr>`,
          )
          .join('')}
      </table>
      <p style="color: #666; font-size: 12px; margin-top: 24px;">Generated by AQ Enterprises website</p>
    `;

    const textBody = rows.map(([k, v]) => `${k}: ${v}`).join('\n');

    await transporter.sendMail({
      from: `"AQ Website Alerts" <${process.env.SMTP_USER}>`,
      to: process.env.LEAD_DESTINATION_EMAIL || process.env.SMTP_USER,
      subject: `New Lead: ${cleanProperty} (${formSource})`,
      text: textBody,
      html: htmlBody,
    });

    return { success: true };
  } catch (error) {
    console.error('[submitLead] Failed to process lead (details omitted).');
    if (process.env.NODE_ENV === 'development') {
      console.error(error);
    }
    return {
      success: false,
      error: 'Internal server error. Please try calling us directly.',
    };
  }
}
