/**
 * @file smtp-provider.ts
 * @description Hardened SMTP lead delivery provider.
 *
 * FEATURES:
 * - Server-side singleton transporter (cached globally to prevent recreation per submission)
 * - Configured connection, greeting, and socket timeouts
 * - Bounded retry mechanism (1 retry with backoff on transient network faults)
 * - Strict HTML escaping against injection
 * - Zero PII in logs or console
 */

import nodemailer, { type Transporter } from 'nodemailer';
import type { LeadDeliveryProvider, LeadDeliveryResult, NormalizedLeadPayload } from './provider';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/** Global cached transporter to prevent connection churn in serverless / Node runtimes. */
let cachedTransporter: Transporter | null = null;

function getSmtpTransporter(): Transporter | null {
  if (cachedTransporter) return cachedTransporter;

  const host = process.env.SMTP_HOST || 'smtp.gmail.com';
  const port = Number(process.env.SMTP_PORT) || 587;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!user || !pass) {
    return null;
  }

  cachedTransporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
    connectionTimeout: 10_000, // 10 seconds
    greetingTimeout: 5_000,    // 5 seconds
    socketTimeout: 15_000,      // 15 seconds
  });

  return cachedTransporter;
}

export class SmtpLeadDeliveryProvider implements LeadDeliveryProvider {
  async deliver(lead: NormalizedLeadPayload): Promise<LeadDeliveryResult> {
    const transporter = getSmtpTransporter();

    if (!transporter) {
      // Structured operational log: NO customer PII is logged.
      console.warn('[SmtpProvider] SMTP not configured. Lead cannot be emailed. Set SMTP_USER and SMTP_PASS in environment.');
      return {
        success: false,
        error: 'Lead delivery service is temporarily unconfigured. Please call or WhatsApp us directly.',
      };
    }

    const rows: [string, string][] = [
      ['Name', lead.name],
      ['Phone', lead.phone],
      ['Property / service', lead.propertyType],
      ['Customer email', lead.email || '—'],
      ['Site address', lead.address || '—'],
      ['Message', lead.message || '—'],
      ['Selected items', lead.orderSummary || '—'],
      ['Requirements / survey request', lead.requirementsSummary || '—'],
      ['Form source', lead.formSource],
      ['Submitted at', lead.submittedAt],
      ['Page path', lead.pagePath || '—'],
      ['Landing page', lead.landingPage || '—'],
      ['Referrer', lead.referrer || '—'],
      ['First-touch source', lead.firstTouchSource || '—'],
      ['UTM source', lead.utmSource || '—'],
      ['UTM medium', lead.utmMedium || '—'],
      ['UTM campaign', lead.utmCampaign || '—'],
      ['UTM content', lead.utmContent || '—'],
      ['UTM term', lead.utmTerm || '—'],
    ];

    const htmlBody = `
      <h2>New Website Lead</h2>
      <table style="text-align: left; border-collapse: collapse; width: 100%; max-width: 580px; font-family: sans-serif; white-space: pre-wrap;">
        ${rows
          .map(
            ([k, v]) =>
              `<tr><th style="padding: 8px 12px; border: 1px solid #ddd; background: #f9f9f9; width: 35%;">${escapeHtml(
                k,
              )}</th><td style="padding: 8px 12px; border: 1px solid #ddd;">${
                k === 'Phone'
                  ? `<a href="tel:${escapeHtml(v)}">${escapeHtml(v)}</a>`
                  : escapeHtml(v)
              }</td></tr>`,
          )
          .join('')}
      </table>
      <p style="color: #666; font-size: 12px; margin-top: 24px;">Generated by AQ Enterprises website lead pipeline</p>
    `;

    const textBody = rows.map(([k, v]) => `${k}: ${v}`).join('\n');

    const mailOptions = {
      from: `"AQ Website Alerts" <${process.env.SMTP_USER}>`,
      to: process.env.LEAD_DESTINATION_EMAIL || process.env.SMTP_USER,
      subject: `New Lead: ${lead.propertyType} (${lead.formSource})`,
      text: textBody,
      html: htmlBody,
    };

    // Resilient delivery: 1 retry with backoff for transient errors
    let lastError: unknown = null;
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        const info = await transporter.sendMail(mailOptions);
        return { success: true, deliveryId: info.messageId };
      } catch (err: unknown) {
        lastError = err;
        // If transient network error, wait 500ms and retry once
        if (attempt === 1) {
          await new Promise((res) => setTimeout(res, 500));
        }
      }
    }

    // Structured operational error — zero PII logged
    console.error('[SmtpProvider] Delivery failed after retries (details redacted).');
    if (process.env.NODE_ENV === 'development' && lastError instanceof Error) {
      console.error(`[SmtpProvider] Error code: ${(lastError as { code?: string }).code || lastError.name}`);
    }

    return {
      success: false,
      error: 'Unable to send your request right now. Please call or WhatsApp us directly.',
    };
  }
}

export const defaultSmtpProvider = new SmtpLeadDeliveryProvider();
